"""create_indexes

Revision ID: 36e771fa3611
Revises: 832fbe9fed83
Create Date: 2024-04-28 14:14:02.497045

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36e771fa3611"
down_revision: Union[str, None] = "832fbe9fed83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_products_category_owner_id"),
        "category",
        ["owner_id"],
        unique=False,
        schema="products",
    )
    op.create_index(
        op.f("ix_products_product_owner_id"),
        "product",
        ["owner_id"],
        unique=False,
        schema="products",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_products_product_owner_id"), table_name="product", schema="products"
    )
    op.drop_index(
        op.f("ix_products_category_owner_id"), table_name="category", schema="products"
    )
    # ### end Alembic commands ###
