"""fix_unique

Revision ID: 6e160767c6ae
Revises: 36e771fa3611
Create Date: 2024-04-28 17:03:07.233375

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e160767c6ae"
down_revision: Union[str, None] = "36e771fa3611"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_products_category_name", table_name="category", schema="products")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_products_category_name",
        "category",
        ["name"],
        unique=True,
        schema="products",
    )
    # ### end Alembic commands ###
