"""init_database

Revision ID: 8f6d31f22861
Revises: 
Create Date: 2024-04-12 16:26:27.248364

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f6d31f22861"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.Date(), nullable=False),
        sa.Column("updated_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="server",
    )
    op.create_index(
        op.f("ix_server_category_id"), "category", ["id"], unique=False, schema="server"
    )
    op.create_index(
        op.f("ix_server_category_name"),
        "category",
        ["name"],
        unique=True,
        schema="server",
    )
    op.create_table(
        "product",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.Date(), nullable=False),
        sa.Column("updated_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["server.category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="server",
    )
    op.create_index(
        op.f("ix_server_product_id"), "product", ["id"], unique=False, schema="server"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_server_product_id"), table_name="product", schema="server")
    op.drop_table("product", schema="server")
    op.drop_index(
        op.f("ix_server_category_name"), table_name="category", schema="server"
    )
    op.drop_index(op.f("ix_server_category_id"), table_name="category", schema="server")
    op.drop_table("category", schema="server")
    # ### end Alembic commands ###
