"""init_database

Revision ID: ba31567f1b96
Revises: 
Create Date: 2024-04-20 16:10:21.394049

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba31567f1b96"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.Date(), nullable=False),
        sa.Column("updated_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="products",
    )
    op.create_index(
        op.f("ix_products_category_id"),
        "category",
        ["id"],
        unique=False,
        schema="products",
    )
    op.create_index(
        op.f("ix_products_category_name"),
        "category",
        ["name"],
        unique=True,
        schema="products",
    )
    op.create_table(
        "product",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.Date(), nullable=False),
        sa.Column("updated_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["products.category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="products",
    )
    op.create_index(
        op.f("ix_products_product_id"),
        "product",
        ["id"],
        unique=False,
        schema="products",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_products_product_id"), table_name="product", schema="products"
    )
    op.drop_table("product", schema="products")
    op.drop_index(
        op.f("ix_products_category_name"), table_name="category", schema="products"
    )
    op.drop_index(
        op.f("ix_products_category_id"), table_name="category", schema="products"
    )
    op.drop_table("category", schema="products")
    # ### end Alembic commands ###
