"""init_db

Revision ID: 46edefe63a85
Revises: 
Create Date: 2024-05-16 14:01:51.577156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46edefe63a85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('balance_replenishment_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='passport'
    )
    op.create_index(op.f('ix_passport_account_id'), 'account', ['id'], unique=False, schema='passport')
    op.create_index(op.f('ix_passport_account_login'), 'account', ['login'], unique=True, schema='passport')
    op.create_table('operation',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('replenishment', 'write_off', 'refund', native_enum=False), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['passport.account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='passport'
    )
    op.create_index(op.f('ix_passport_operation_id'), 'operation', ['id'], unique=False, schema='passport')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passport_operation_id'), table_name='operation', schema='passport')
    op.drop_table('operation', schema='passport')
    op.drop_index(op.f('ix_passport_account_login'), table_name='account', schema='passport')
    op.drop_index(op.f('ix_passport_account_id'), table_name='account', schema='passport')
    op.drop_table('account', schema='passport')
    # ### end Alembic commands ###
