"""fix_unique_login

Revision ID: e5f119ad6905
Revises: eb562ee5dd37
Create Date: 2024-04-29 00:56:15.716785

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5f119ad6905"
down_revision: Union[str, None] = "eb562ee5dd37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_passport_account_login", table_name="account", schema="passport")
    op.create_index(
        op.f("ix_passport_account_login"),
        "account",
        ["login"],
        unique=True,
        schema="passport",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_passport_account_login"), table_name="account", schema="passport"
    )
    op.create_index(
        "ix_passport_account_login",
        "account",
        ["login"],
        unique=False,
        schema="passport",
    )
    # ### end Alembic commands ###
